### PR TITLE
Add inputstream.ffmpegdirect addon

### PR DESCRIPTION
**Pull request by phunkyfish**
Add new binary addon repo

### CODE REVIEW

**Review by AlwinEsch — APPROVED** [review]

**Comment by MilhouseVH** [comment]
Are the more recent changes on this zvbi github mirror of any value?

https://github.com/jwilk-mirrors/zvbi/compare/zvbi-0-2-35...trunk

Maybe use this mirror as an upstream source instead of the sourceforge?

**Comment by phunkyfish** [comment]
Nice find. I didn’t realise there was a newer version.

**Comment by MilhouseVH** [comment]
Credit to @CvH who mentioned it to me on LibreELEC Slack. :)

Our PR btw is here: https://github.com/LibreELEC/LibreELEC.tv/pull/4109

**Comment by phunkyfish** [comment]
It’s not been released since latest the version we have even though there has been around 30 commits since.

**Comment by phunkyfish** [comment]
I tried to email the author and asked will he do a release but the address does not work.

Without an official release I’m not sure we should upgrade.

**Comment by CvH** [comment]
> Without an official release I’m not sure we should upgrade.

not sure it has any benefit that you wait for an official release at an dead project ;)

**Comment by MilhouseVH** [comment]
If nothing else, maybe cherry-pick any of those commits/patches that seem to make sense.

**Comment by phunkyfish** [comment]
I guess we could make our own fork and release from that, maybe under the xbmc org so it stays put.

Although I will say I’ve tested this and it does work as is so maybe one for the todo list.

**Pull request merged**
