### PR TITLE
Add pvr.rtl.radiofm FM Radio Receiver PVR add-on to binary repo (part 2)

### PR DESCRIPTION
**Pull request by Hedda**
Add AlwinEsch's pvr.rtl.radiofm FM Radio Receiver PVR add-on to the official repository for Kodi binary add-ons  ( part 2 = platforms.txt ).

Not tested compiling on all platforms so adding platforms.txt as a seperate "part 2" pull request.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
he should request it himself

**Comment by Hedda** [comment]
https://github.com/AlwinEsch/pvr.rtl.radiofm/issues/1

**Comment by Rechi** [comment]
@Hedda the addon doesn't have to be placed at https://github.com/kodi-pvr/ to get included here.
You just have to convince the author to request the include himself.

**Comment by Hedda** [comment]
@Rechi Thanks for the info. Been trying to convince @AlwinEsch (who is also a member to Team Kodi):

https://github.com/AlwinEsch/pvr.rtl.radiofm

First requested this over two years ago and have requested it again once year ago so time again now:

https://github.com/AlwinEsch/pvr.rtl.radiofm/issues/1

This addon needs to be updated first but it would be very nice to see it in maybe the Kodi 18 release ;)

**Comment by MartijnKaijser** [comment]
You can nag some one as many times as you want but if he doesn't wan't to it won't happen!

**Comment by Hedda** [comment]
@MartijnKaijser I would not call three requests over three years nagging, and besides that, AlwinEsch said 6-months ago that he will "soon" update this addon to the new style of the latest PVR API, so he should hopefully not take offence for asking again now.

**Pull request closed without merging**
