### PR TITLE
add inputstream.mpd dash addon

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@mapfau it fails to build on all platforms

**Comment by ghost** [comment]
fixed, I'll be more careful in the future before I do commits

**Comment by MartijnKaijser** [comment]
Good suggestions is doing travis and appveyor CI building
https://github.com/kodi-pvr/pvr.hts/blob/master/.travis.yml
https://github.com/kodi-pvr/pvr.hts/blob/master/appveyor.yml
for examples

**Comment by ghost** [comment]
i have never done this before - is there any howto about this topic?

Edit: I'll ask google and come back if anything is not working....

**Pull request merged**
