### PR TITLE
set fixed versions

### PR DESCRIPTION
**Pull request by notspiff**
This sets tagged versions for the add-ons i maintain.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Many thx. Only expected you tagging them in your repo :)

**Comment by MartijnKaijser** [comment]
@notspiff 
There's still
vortex
vsxu
on "master"

**Comment by notspiff** [comment]
I dont do windows addons. will send vsxu asap

7. des. 2016 18:47 skrev "Martijn Kaijser" <notifications@github.com>:

**Comment by MartijnKaijser** [comment]
ah sorry, overlooked it was from Montellese.

**Comment by notspiff** [comment]
disable vsxu. it is too dependent on glew for me to bother fixing this up
(and GLEW cannot be used with kodi any longer).

**Comment by notspiff** [comment]
right. me being me i just couldn't give in. i have it running again but
right now it's a giant hack fest that i cannot push. i will clean it up
eventually, but still, disable for now.

**Pull request merged**
