### PR TITLE
[pvr.freebox] 2.0.0

### PR DESCRIPTION
**Pull request by aassif**
This PVR client allows French "Free" subscribers to watch channels and manage recordings through Kodi instead of their "Freebox".
It's also compatible with the provider's EPG.

As you can see, it's based on a Matrix branch and it's tested on Linux, LibreELEC (RPi2 + x86_64) and Android (ARMv7a + AArch64).

### CODE REVIEW

**Comment by ksooo** [comment]
> As you can see, it's based on a Matrix branch and it's tested on Linux, LibreELEC (RPi2 + x86_64) and Android (ARMv7a + AArch64).

 Well, I doubt that the addon has been tested on Matrix as it will neither compile nor run on Matrix in it's current state. You need to update the sources to PVR addon API 6.0.0 for Matrix.

**Comment by aassif** [comment]
So far, I've only rebased the repo and created a Matrix branch for the addon.
I'm currently trying to compile Kodi's latest "master" branch.

**Comment by aassif** [comment]
Matrix build OK!

**Comment by ksooo** [comment]
Great.

What do I need to test this addon myself? Any account / subscription / hardware?

**Comment by aassif** [comment]
If you were a French resident, you would need a subscription to the French provider called "Free" and they would send you their "Freebox".
Nevertheless, this box provides a VPN server and I can set an account up for testing purposes.
Would that be OK?

**Comment by ksooo** [comment]
Sure. Please send the details to ksooo at kodi.tv.

**Comment by aassif** [comment]
As soon as I'm back home!

**Comment by ksooo** [comment]
No hurry.

**Comment by ksooo** [comment]
I'm unable to build this addon.

```
Scanning dependencies of target pvr.freebox
[ 75%] Creating directories for 'pvr.freebox'
[ 78%] No download step for 'pvr.freebox'
[ 81%] No patch step for 'pvr.freebox'
[ 84%] No update step for 'pvr.freebox'
[ 87%] Performing configure step for 'pvr.freebox'
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
CMake Error at /Users/Shared/xbmc-depends/x86_64-darwin18.5.0-native/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /Users/Shared/xbmc-depends/x86_64-darwin18.5.0-native/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Users/Shared/xbmc-depends/x86_64-darwin18.5.0-native/share/cmake-3.12/Modules/FindOpenSSL.cmake:412 (find_package_handle_standard_args)
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
```

@Rechi do you have an idea how to fix that?

**Comment by wsnipex** [comment]
depends are missing completely, so this can only ever compile on linux  with system libraries atm.

**Comment by ksooo** [comment]
@aassif do you have any interest in fixing above mentioned build issues? Otherwise your addon has no chances to get accepted.

**Comment by aassif** [comment]
My understanding was that the depends build system was currently incomplete.
Given OpenSSL is quite common, I didn't think there was something to do on my side.
If I'm wrong, I'll do everything I can :)

**Comment by ksooo** [comment]
> I didn't think there was something to do on my side. If I'm wrong, I'll do everything I can :)

 Maybe @Rechi  or @wsnipex can assist you.

**Comment by aassif** [comment]
> depends are missing completely, so this can only ever compile on linux with system libraries atm.

@wsnipex What did you mean by "atm"? What should I do?

**Comment by wsnipex** [comment]
you have to add build dependencies to your addon. see almost all other binary addons for examples.
https://github.com/xbmc/inputstream.rtmp/tree/Leia/depends also uses openssl

**Comment by aassif** [comment]
I did some tests yesterday but I couldn't build the addon.
First, I uninstalled every package required (zlib1g-dev, libssl-dev, rapidjson-dev).
Then, I created a depends tree just like you showed me.
Zlib and RapidJSON were built and found in the right location but OpenSSL kept trying to install itself in "/usr/local/".
I probably missed something. I'll take another look tonight!

**Comment by aassif** [comment]
OK.
I had to modify "depends/common/openssl/CMakeLists.txt" to explicitly specify the prefix.
Moreover, it seems like all the "sed -ie ..." lines have become useless as the "apps test" pattern never occurs any more.
@ksooo Could you please give it another try?

**Comment by ksooo** [comment]
One step closer. Dependencies are found and built, then it tries to compile the addon, but at least on macOS this fails:

<pre>
-- Build files have been written to: /Users/kai/src/github/ksooo/xbmc/tools/depends/target/binary-addons/macosx10.14_x86_64-target-debug/pvr.freebox-prefix/src/pvr.freebox-build
[ 94%] Performing forcebuild step for 'pvr.freebox'
Force build of pvr.freebox
[ 96%] Performing build step for 'pvr.freebox'
Scanning dependencies of target pvr.freebox
[ 33%] Building CXX object CMakeFiles/pvr.freebox.dir/src/client.cpp.o
[ 66%] Building CXX object CMakeFiles/pvr.freebox.dir/src/Freebox.cpp.o
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:272:22: error: use of undeclared identifier 'HOST_NAME_MAX'
      char hostname [HOST_NAME_MAX + 1];
                     ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:273:30: error: use of undeclared identifier 'HOST_NAME_MAX'
      gethostname (hostname, HOST_NAME_MAX);
                             ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:1107:17: warning: enumeration value 'NONE' not handled in switch [-Wswitch]
        switch (q.type)
                ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:1107:17: note: add missing switch cases
        switch (q.type)
                ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:1190:11: warning: enumeration value 'DEFAULT' not handled in switch [-Wswitch]
  switch (source)
          ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:1190:11: note: add missing switch cases
  switch (source)
          ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:1218:11: warning: enumeration value 'DEFAULT' not handled in switch [-Wswitch]
  switch (quality)
          ^
/Users/kai/src/github/ksooo/kodi-pvr-addons/pvr.freebox/src/Freebox.cpp:1218:11: note: add missing switch cases
  switch (quality)
          ^
3 warnings and 2 errors generated.
make[7]: *** [CMakeFiles/pvr.freebox.dir/src/Freebox.cpp.o] Error 1
make[6]: *** [CMakeFiles/pvr.freebox.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [pvr.freebox-prefix/src/pvr.freebox-stamp/pvr.freebox-build] Error 2
make[3]: *** [CMakeFiles/pvr.freebox.dir/all] Error 2
make[2]: *** [CMakeFiles/pvr.freebox.dir/rule] Error 2
make[1]: *** [pvr.freebox] Error 2
touch .installed-macosx10.14_x86_64-target-debug
</pre>

**Comment by ksooo** [comment]
If a hack away the compile error (by defining HOST_NAME_MAX) the addon compiles, but does not link, because implementation for new API 6.0.0 function `FillBuffer` is missing. Just 'implement it as `void FillBuffer(bool mode) {}` in client.cpp.

<pre>
[ 66%] Linking CXX shared library pvr.freebox.dylib
Undefined symbols for architecture x86_64:
  "_FillBuffer", referenced from:
      _get_addon in client.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[7]: *** [pvr.freebox.2.0.0.dylib] Error 1
make[6]: *** [CMakeFiles/pvr.freebox.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [pvr.freebox-prefix/src/pvr.freebox-stamp/pvr.freebox-build] Error 2
make[3]: *** [CMakeFiles/pvr.freebox.dir/all] Error 2
make[2]: *** [CMakeFiles/pvr.freebox.dir/rule] Error 2
make[1]: *** [pvr.freebox] Error 2
touch .installed-macosx10.14_x86_64-target-debug
</pre>

**Comment by ksooo** [comment]
After fixing the compile and link error, the addon loads just fine - channel listing and epg grid seem to work, but 

* channel playback does not start (using the vpn you kindly provided me for testing).
* I see a popup "Authorize Kodi on Freebox Server" every 5 secs or so.

(only did a very very quick check)

**Comment by ksooo** [comment]
Playback problem log:

<pre>
2019-05-21 23:47:13.042493+0200 kodi.bin[57322:1150552] Debug Print: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.freebox_201.pvr
2019-05-21 23:47:13.043212+0200 kodi.bin[57322:1151061] Debug Print: Creating InputStream
2019-05-21 23:47:13.043959+0200 kodi.bin[57322:1151061] Debug Print: Creating Demuxer
2019-05-21 23:47:13.382173+0200 kodi.bin[57322:1151061] [si_destination_compare] send failed: Invalid argument
2019-05-21 23:47:23.891192+0200 kodi.bin[57322:1151061] Debug Print: could not find codec parameters for rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd
2019-05-21 23:47:23.891676+0200 kodi.bin[57322:1151061] Debug Print: OpenDemuxStream - Error creating demuxer
</pre>

**Comment by aassif** [comment]
> If a hack away the compile error (by defining HOST_NAME_MAX) the addon compiles, but does not link, because implementation for new API 6.0.0 function `FillBuffer` is missing. Just 'implement it as `void FillBuffer(bool mode) {}` in client.cpp.

As you might have already seen, I fixed those issues.

> I see a popup "Authorize Kodi on Freebox Server" every 5 secs or so.

The popup means that I need to physically authorize the app on the box.
To get rid of it, we should sync your next try.
Nevertheless, it shouldn't affect playback. Only recordings.

> channel playback does not start (using the vpn you kindly provided me for testing).

I've been using the VPN trick to access the server from behind a router.
I suppose it should work from outside but I'm not sure.

How do you connect to the VPN? PPTP or OpenVPN?
In my experiments, I was using the OpenVPN way.

**Comment by aassif** [comment]
> In my experiments, I was using the OpenVPN way.

In fact, PPTP works too.
Once connected, can you open the RTSP stream in something like VLC?

**Comment by ksooo** [comment]
> Once connected, can you open the RTSP stream in something like VLC?

 Yes, no problem to play the stream with VLC.

**Comment by aassif** [comment]
> Yes, no problem to play the stream with VLC.

If you create a `.strm` file containing the URL then open it with Kodi, does it work too?

Could you also delete the file `~/.kodi/userdata/addon_data/pvr.freebox/app_data.txt`?

**Comment by ksooo** [comment]
> Could you also delete the file ~/.kodi/userdata/addon_data/pvr.freebox/app_data.txt?

 app_token.txt, right? removing it or using strm file: no change in behavior.

 Always same error in the log:

<pre>
2019-05-22 13:53:44.103787+0200 kodi.bin[61083:1213210] [si_destination_compare] send failed: Invalid argument
</pre>

**Comment by aassif** [comment]
> **app_token.txt**, right? removing it or using strm file: no change in behavior.

Indeed.
Removing it allowed me to grant access to recordings.

If Kodi can't play the `.strm` file but VLC can, it could be a Kodi issue.
Could you please check with other RTSP streams?

**Comment by aassif** [comment]
> Could you please check with other RTSP streams?

I suppose other PVR clients rely on RTSP and I know you're no beginner.
It's just that, other than port forwarding or such, I don't have a clue.

**Comment by ksooo** [comment]
Have no other rtsp-using pvr client at hand, but tried with another (non freebox) rtsp stream via strm file. Works like a charm in Kodi.

**Comment by aassif** [comment]
Well, I'm sorry it's taking this long.
As you can see in the [source](https://github.com/aassif/pvr.freebox/blob/f520a83db55b57e6fe4a7a3460d7133ae5e57cd4/src/Freebox.cpp#L584), I pass the stream URL to Kodi just like many clients do.
Even though I can trick the server accessing it locally from behind a router, I never tried from outside.
Maybe the server sniffs your packets and blocks them?
I will try to access my Freebox from somewhere else.
Did you try both PPTP and OpenVPN?

**Comment by ksooo** [comment]
Only OpenVPN (actually Tunnelblick on  macOS).

**Comment by ksooo** [comment]
Well well well, I had to disable my local firewall to make playback work. :-/

**Comment by aassif** [comment]
@ksooo Isn't it great news?

**Comment by ksooo** [comment]
@aassif from your pov, are we ready to merge this?

And could you please give me push access to https://github.com/aassif/pvr.freebox ? I would like to be able to make smaller non-functional changes to the addon myself, like I do with all other pvr addons.

@Rechi could we please setup jenkins support for the new addon? Matrix and later only.

**Comment by aassif** [comment]
Fine by me :)
I just gave you push access!

**Comment by ksooo** [comment]
> I just gave you push access!

 Thanks.
 Could you please set the default branch to "Matrix"?

**Comment by aassif** [comment]
Done!

**Pull request merged**
