### PR TITLE
changed: build audio decoders on all platforms

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by Rechi** [comment]
compile tested for osx, ios & android
windows was tested with appveyor

**Comment by laserio** [comment]
Hi, I would to build audiodecoder.dsd to qnap nas platform (via hdmi interface, there an unsupported kodi version). I use Ubuntu 16.04, do you think is that possible?

**Comment by notspiff** [comment]
dsd is natively supported, for a few years no need for the add-on.

**Comment by laserio** [comment]
Beacause I tried to play some dsf/dff file but the dac that I used (full
dsd support on pc with usb cable) didn't recognize them: it plays them but
with pcm decoding, at 192Khz.
There's some congiguration setting to change? I only see the max audio
output resolution (44.1-192 khz).

Thanks!


-- 
-- 
Lorenzo Aserio

Direzione Sistemi Informativi, Portale, E-learning
Sezione Prototipazione e Management Dei Servizi Ict
Università degli Studi di Torino
www.unito.it
Via Po, 31 - 10124 Torino - Italy
Tel: +39 011/670.2265
Fax: +39 011/236.2477
Email: lorenzo.aserio@unito.it

2018-03-22 9:36 GMT+01:00 Arne Morten Kvarving <notifications@github.com>:

**Comment by notspiff** [comment]
there is no dsd passthrough support, neither with nor without the decoder add-on. they are both decoders.

**Comment by laserio** [comment]
Ok, than it's decoding DSD in PCM (also the add.on). I thought that DSD
need a passthrough, but I saw only Dolby and DTS and I tried other ways...
I hope for a DSD passthrough in the new kodi release!

Thank you very much and best regards!

Lorenzo


-- 
-- 
Lorenzo Aserio

Direzione Sistemi Informativi, Portale, E-learning
Sezione Prototipazione e Management Dei Servizi Ict
Università degli Studi di Torino
www.unito.it
Via Po, 31 - 10124 Torino - Italy
Tel: +39 011/670.2265
Fax: +39 011/236.2477
Email: lorenzo.aserio@unito.it

2018-03-22 10:04 GMT+01:00 Arne Morten Kvarving <notifications@github.com>:

**Pull request merged**
