### PR TITLE
Add pvr.sledovanitv.cz addon, attempt#2

### PR DESCRIPTION
**Pull request by palinek**
Hi,
this is client for the Czech IP TV provider https://sledovanitv.cz (works also for Slovakian subscribers - https://sledovanietv.sk).

> Go, write them an email, asking for their permission to use your client for their services. Once we've seen their okay, we can include your addon in our offial repo.

Hereafter are the statements of the provider as requested:
- translated version of emails (reviewed google translate)
> Date: Wed, 18 Apr 2018 22:47:22 +0200
> Subject: Enduser device
> From: Palo Kisa <palo.kisa@gmail.com>
> To: info@sledovanitv.cz
> 
> Good evening,
>  is it possible to use your service on custom device (not officialy supported by your company) without being prosecuted or blocked from your side?
> 
> Assuming this based on general commercial conditions, catch 4.1:
> "The user is obliged to supply the hardware and software resources including their installation, input and output devices, including the television set (hereinafter referred to as the "User's Device") and their functionality and compatibility with the IPTV Service in order to connect to the endpoint of the Operator's network . The operator is not responsible for the functionality or operation of these User's Devices. The connection of devices other than equipment tested by the Operator can only be the sole responsibility of the User and only if such equipment is designated and properly certified for the European Union market. The list of devices tested by Operator (including software solutions) is listed on the website. In the event of connections other than those approved by the Operator, the Operator shall not be liable for the functionality and quality of the IPTV Service, and in the event of the IPTV Service being rendered inoperable, unavailable or diminished, the Operator shall not guarantee the level of service provided."
> 
> thank you
> ￼
> palo kisa
> 
> ----
> 
> Date: Thu, 19 Apr 2018 11:06:34 +0200
> From: Jana Hajdova <podpora@sledovanitv.cz>
> Subject: Re: Enduser device [REQ-003526]
> To: <palo.kisa@gmail.com>
> Cc: <info@sledovanitv.cz>
> 
> Good morning,
> 
> if we are talking e.g. about an unsupported set-top box (this is the most common case you describe), of course you can use it and no punishment or blocking action will be taken, but we can not guarantee the full functionality of the service on such a device. Specifically, for 90% of non-supported Android boxes controlling doesn't work correctly, because the app is for mobile devices.
> 
> With best wishes
> Jana Hajdová
> SledovaniTV.cz
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:16:19 +0200
> Subject: Re: Enduser device [REQ-003526]
> From: Palo Kisa <palo.kisa@gmail.com>
> To: Jana Hajdova <podpora@sledovanitv.cz>
> Cc: info@sledovanitv.cz
> 
> Good morning.
> 
> Thank you for the information. I didn't talk about android device, but I'm curious about a device equiped with SW Kodi (http://kodi.tv/).
> 
> So I wonder if you would try to prevent development/use of plugins bringing support for sledovanitv.cz into Kodi?
> 
> I deduce (because your big competitive advantage is exactly a wide spectrum of supported devices), that it shouldn't be a problem... but just to be sure.
> 
> thank you
> 
> palo kisa
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:23:34 +0200
> From: Jana Hajdova <podpora@sledovanitv.cz>
> Subject: Re: Enduser device [REQ-003526]
> To: <palo.kisa@gmail.com>
> Cc: <info@sledovanitv.cz>
> 
> Good morning,
> 
> thank you for bringing more information - with Kodi and VLC the problem is different, we were also originally supporting them, but these players do not support DRM, so we have to end their support for copyright protection, for which violations we could have been severely penalized.
> 
> So you can use (even for KODI playback there are some plugins - not from us - available) VLC playlist, which is available on the web in the settings page https://sledovanietv.sk/account/services, but it is pretty trimmed, there are not all channels nor HD quality in it. It is also possible that we will completely drop this playlist in the future.
> 
> With best wishes
> Jana Hajdová
> SledovaniTV.cz
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:37:34 +0200
> Subject: Re: Enduser device [REQ-003526]
> From: Palo Kisa <palo.kisa@gmail.com>
> To: Jana Hajdova <podpora@sledovanitv.cz>
> Cc: info@sledovanitv.cz
> 
> Good morning.
> 
> Thank you.
> 
> But once again to avoid misunderstanding:
> 
> > So you can use (even for KODI playback there are some plugins - not from us - available)
> 
> Can you, please, state, that sledovani.tv does not have problem with existing, eventualy newly created plugins for Kodi and does not take actions to reject distribution of such plugins?
> 
> thank you
> 
> palo kisa
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:38:34 +0200
> From: Jana Hajdova <podpora@sledovanitv.cz>
> Subject: Re: Enduser device [REQ-003526]
> To: <palo.kisa@gmail.com>
> Cc: <info@sledovanitv.cz>
> 
> 
>  Good morning,
> 
> we do not restrict these plugins, but neither do we support their development.
> 
> With best wishes
> Jana Hajdová
> SledovaniTV.cz

- original version of emails
> Date: Wed, 18 Apr 2018 22:47:22 +0200
> Subject: Koncove zariadenie
> From: Palo Kisa <palo.kisa@gmail.com>
> To: info@sledovanitv.cz
> 
> Dobry den,
>  je mozne pouzivat vasu sluzbu na vlastnom zariadeni (nie oficialne vami podporovanom) bez hrozby postihu alebo blokacie z vasej strany?
> 
> Vychadzam z vseobecnych podmienok, clanok 4.1:
> "Uživatel je povinen si zabezpečit hardwarové i softwarové prostředky včetně jejich instalace, vstupní a výstupní zařízení, včetně televizního přijímače (dále jen „Zařízení Uživatele“) a jejich funkčnost a kompatibilitu se Službou IPTV tak, aby bylo možné připojení ke koncovému bodu sítě Provozovatele. Provozovatel neodpovídá za funkčnost či provoz těchto Zařízení Uživatele. Připojení jiných zařízení než zařízení otestovaných Provozovatelem je možné jen na výlučnou odpovědnost Uživatele a pouze za předpokladu, že takové zařízení je určeno a řádně certifikováno pro trh Evropské unie. Seznam Provozovatelem otestovaných zařízení (včetně softwarových řešení) je uveden na internetových stránkách. V případě připojení jiných zařízení než schválených Provozovatelem nenese Provozovatel odpovědnost za funkčnost a kvalitu Služby IPTV a v případě nefunkčnosti, nedostupnosti či snížení dostupnosti Služby IPTV negarantuje Provozovatel v těchto případech úroveň poskytovaných služeb."
> 
> dakujem
> ￼
> palo kisa
> 
> ----
> 
> Date: Thu, 19 Apr 2018 11:06:34 +0200
> From: Jana Hajdova <podpora@sledovanitv.cz>
> Subject: Re: Koncove zariadenie [REQ-003526]
> To: <palo.kisa@gmail.com>
> Cc: <info@sledovanitv.cz>
> 
> Dobrý deň,
> 
> pokiaľ ide napríklad o nepodporovaný set-top box (to je najčastejší prípad situácie ako popisujete), tak samozrejme ho používať môžete a nijaký postih ani blokácia Vás za to čakať nebude, ale nemôžeme Vám zaručiť plnohodnotnú funkčnosť služby na takomto zariadení. Konkrétne na nepodporovaných Android boxoch v 90 % prípadov nefunguje v poriadku ovládanie, pretože aplikácia je určená pre mobilné zariadenia.
> 
> S pozdravem a přáním pěkného dne
> Jana Hajdová
> SledovaniTV.cz
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:16:19 +0200
> Subject: Re: Koncove zariadenie [REQ-003526]
> From: Palo Kisa <palo.kisa@gmail.com>
> To: Jana Hajdova <podpora@sledovanitv.cz>
> Cc: info@sledovanitv.cz
> 
> Dobry den.
> 
> Dakujem za info. Nemal som na mysli android zariadenie, ale zariadenie so SW vybavou Kodi (http://kodi.tv/).  
> 
> Zaujimalo by ma teda, ci by z vasej strany bola snaha branit vyvoju/pouzivaniu plugin-u pre podporu sledovani.tv do Kodi?
> 
> Logicky mi (kedze vasou velkou konkurencnou vyhodou je prave siroke spektrum podporovanych zariadeni) vychadza, ze by v tom ziaden problem nemal byt... ale pre istotu.
> 
> 
> dakujem
> 
> palo kisa
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:23:34 +0200
> From: Jana Hajdova <podpora@sledovanitv.cz>
> Subject: Re: Koncove zariadenie [REQ-003526]
> To: <palo.kisa@gmail.com>
> Cc: <info@sledovanitv.cz>
> 
> Dobrý deň,
> 
> ďakujem za doplnenie - u Kodi a VLC je problém iný, pôvodne sme ich tiež podporovali ale tieto prehrávače nemajú podporu DRM a teda ich podporu sme teda museli zatrhnuť z dôvodu ochrany autorských práv, za ktorých porušovanie nám hrozili výrazné postihy.
> 
> Môžete teda používať (aj pre prehrávanie v KODI, nejaké pluginy - nie od nás - sú dostupné) VLC playlist ktorý máme dostupný na webe v nastaveniach https://sledovanietv.sk/account/services ale je dosť osekaný, nie sú tam všetky kanály ani HD kvalita. Je tiež možné že v budúcnosti ten playlist úplne zrušíme.
> 
> S pozdravem a přáním pěkného dne
> Jana Hajdová
> SledovaniTV.cz
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:37:34 +0200
> Subject: Re: Koncove zariadenie [REQ-003526]
> From: Palo Kisa <palo.kisa@gmail.com>
> To: Jana Hajdova <podpora@sledovanitv.cz>
> Cc: info@sledovanitv.cz
> 
> Dobry den.
> 
> Dakujem.
> 
> Ale este predsa nech predideme nedorozumeniu:
> 
> > Môžete teda používať (aj pre prehrávanie v KODI, nejaké pluginy - nie od nás - sú dostupné) 
> 
> Mozte, prosim, potvrdit, ze sledovani.tv nema problem s existujucimi, pripadne novovzniknutymi pluginmi pre Kodi a nekona kroky pre zamedzenie distribucie takychto pluginov ?
> 
> dakujem
> 
> palo kisa
> 
> ---
> 
> Date: Thu, 19 Apr 2018 11:38:34 +0200
> From: Jana Hajdova <podpora@sledovanitv.cz>
> Subject: Re: Koncove zariadenie [REQ-003526]
> To: <palo.kisa@gmail.com>
> Cc: <info@sledovanitv.cz>
> 
> 
>  Dobrý deň,
> 
> tie pluginy neobmedzujeme, ale ani nepodporujeme ich vývoj.
> 
> S pozdravem a přáním pěkného dne
> Jana Hajdová
> SledovaniTV.cz

### CODE REVIEW

**Comment by peak3d** [comment]
@palinek you may want to let then know that we support DRM.
I guess, that you also have implemented DRM / inputstream.adaptive, right?

**Comment by palinek** [comment]
> I guess, that you also have implemented DRM / inputstream.adaptive, right?

No, it is not needed for the "basic functionality" of using this provider (watching basic channels live streams & personal recordings). IMO the DRM comes into play for HBO and such, which they also resell.

**Comment by palinek** [comment]
Any news here?

**Comment by ksooo** [comment]
ATM, I'm really very busy with real life. So, please be patient. When I find some spare time, I will look at this. Has no high priority for me, tbh.

**Comment by palinek** [comment]
Still no luck with reviewing this?

**Comment by palinek** [comment]
ping

**Comment by ksooo** [comment]
Still not high priority, sorry. increasing ping frequency won't change  anything.

**Comment by palinek** [comment]
> increasing ping frequency won't change anything.

Delay between pings 7 days, 21 days, 1 month is not exactly an increasing sequence :)

I just don't get what is here to do for you. As i see it, it is just about saying go/no-go (maybe after a quick 15min. review of the code).

**Comment by ksooo** [comment]
Don't get how the hell you could know how long a code review will take.

Being demanding will not speed up things. We're talking about my spare time, dude. And I'm the only one to decide how I spend it.

**Comment by palinek** [comment]
> Don't get how the hell you could know how long a code review will take.

I definitely don't know... I just see, that you're familiar with the pvr plugins and this one is really simple (originally based on iptvsimple).  And until now I didn't know you want/need to do the code review (it wasn't clearly stated and still I'm just assuming it just because of your firm reaction). 

So is this the case? Do you need to do a thorough code review of the plugin?

> And I'm the only one to decide how I spend it.

As every one of us.

**Comment by peak3d** [comment]
I took some time looking over the code and it looks sane for me.

**Comment by ksooo** [comment]
Guys, I will deal with this when my time and mood permits. Just stay patient. The world will continue to spin even if this PR has to wait some more time.

**Comment by ksooo** [comment]
Ready to go, thanks for your patience, @palinek

**Review by ksooo — COMMENTED** [review]
Good to go.

**Pull request merged**
