### PR TITLE
add vfs.sacd

### PR DESCRIPTION
**Pull request by notspiff**
This adds filesystem support for SuperAudioCD iso's.

It's somewhat suboptimal but it is better than nothing. The problem is that the audio streams on SACD's have DST compression applied. After decode they are regular DSD streams. As DST is not supported at the proper layer (demux) I have to on-the-fly decode in the input stream resulting in suboptimal performance, no seek support and only estimated runtimes.

Requires https://github.com/xbmc/xbmc/pull/12004

### CODE REVIEW

**Comment by candrews** [comment]
_bump_

**Comment by notspiff** [comment]
note i've gotten some reports the add-on is rather buggy. however, of course it won't bite anyone who doesn't ask to be bitten.

**Comment by packrobottom** [comment]
how does one add this to kodi?

**Comment by MartijnKaijser** [comment]
@notspiff should this be added?

**Comment by notspiff** [comment]
it won't do any harm, but it is rather work in progress. it works for my 1 sacd iso, but i've had reports it doesn't play with 50% of em or so. your choice.

**Comment by HeresJonny** [comment]
Since this is just an SACD .iso parser, could this be added to main, please? Shouldn't aversely affect anyone, the only problem being that not all SACDs will be read. It's still a start, though.

**Comment by HeresJonny** [comment]
bump

**Comment by notspiff** [comment]
changed to point to xbmc repo. please merge now.

**Pull request merged**
