### PR TITLE
Add pvr.waipu

### PR DESCRIPTION
**Pull request by flubshi**
waipu.tv is a german TV streaming provider that provides access to more than 90 TV channels. Besides live streams, it provides EPG data and recordings.

The current implementation is inspired by the great pvr.zattoo addon, created by @rbuehlma (thanks!) - maybe you, as a rapidjson expert, could take a look at this addon to suggest improvements? :)

@ksooo I tried my best to make this addon compliant. What changes are necessary to get accepted? Do you prefer to move the pvr.waipu repo to kodi-pvr?

### CODE REVIEW

**Comment by ksooo** [comment]
Thank you very much for your contribution.

At a very first and quick glance the addon code looks very good.

Currently I'm a bit short on time, sorry for that. I will come back to you on this as soon as my time permits.

**Comment by flubshi** [comment]
Thanks @ksooo - I think my contribution is tiny compared to your great work on the kodi pvr components! :)

I have great news: Today I received an email reply from waipu that they are acquiescing to the development of this plugin. We agreed on some requirements (user-agent, disclaimer, ...) the latest version of this pvr plugin now fulfills.

Current status of the plugin: It is in daily use for more than a month without any noticeable issues.


For getting accepted in this repo: I know you are a volunteer (thanks!) with limited time - but would it be possible to provide a rough ETA?

**Comment by ksooo** [comment]
> Today I received an email reply from waipu that they are acquiescing to the development of this plugin. We agreed on some requirements (user-agent, disclaimer, ...) the latest version of this pvr plugin now fulfills.

 That's actually good news.

> For getting accepted in this repo: ... would it be possible to provide a rough ETA?

 We will start v19 alpha dev cycle soon. This is the right time for integrating new pvr addons to get early feedback.

**Comment by ksooo** [comment]
@flubshi could you please give me write access to your repo? I'd like to prepare your repo for the next step - including pvr.waipu in official Kodi v19 builds... If I do this instead of instructing you, this will speed up things.

**Comment by flubshi** [comment]
You should have received an invitation. Feel free to modify whatever is necessary :)

Should I modify this PR to merge into Matrix branch?

**Comment by ksooo** [comment]
> You should have received an invitation. Feel free to modify whatever is necessary :)

 Thanks. Will do tomorrow.

> Should I modify this PR to merge into Matrix branch?

 Yes, please. AFAIK, you need to resubmit the PR if you want to change the target branch.

**Comment by ksooo** [comment]
> flubshi changed the base branch from master to Matrix 16 hours ago

 How did you do that? obviously no need to resubmit the PR. Curious...

**Comment by flubshi** [comment]
"Edit PR" allows to modify the PR title and adds a dropdown after "flubshi wants to merge 1 commit into" - this allows to change the target branch. :)

**Comment by ksooo** [comment]
> "Edit PR" allows to modify the PR title and adds a dropdown after "flubshi wants to merge 1 commit into" - this allows to change the target branch. :)

 Cool. Thanks for sharing this.

**Review by ksooo — APPROVED** [review]
Thanks. Now, your addon is officially part of Kodi. :-)

**Pull request merged**
