### PR TITLE
Add peripheral.joystick

### PR DESCRIPTION
**Pull request by garbear**

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks.

**Comment by MartijnKaijser** [comment]
FYI i find it kinda unacceptable that a mandatory binary addon is not with XBMC organisation on github. This should certainly be moved.

**Comment by Montellese** [comment]
It's not mandatory. Kodi works fine without it. You just can't use any joysticks without it. A lot of the other addons are under other github accounts as well.

**Comment by garbear** [comment]
@MartijnKaijser the add-on is hosted in the kodi-game organization. Feel free to make this organization officially part of kodi. If we get additional periperal add-ons, then we can consider consolidating them somewhere

**Pull request merged**
