### PR TITLE
import inputstream.rtmp

### PR DESCRIPTION
**Pull request by notspiff**
I fully expect this to break in various ways but I can't get further without testing.

Windows is excluded as we still need to figure out how to bring in the dependencies there.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Can this just be merged or does core needs some additional changes? 
If it causes to much issues I'll disable it temporary end of the month just before alpha release.

**Comment by akva2** [comment]
no changes needed in core. it can be merged, worst that happens is that jenkins doesn't like building it.

**Comment by MartijnKaijser** [comment]
Test build running 
http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1429/

**Comment by MartijnKaijser** [comment]
Only linux was successful

**Comment by notspiff** [comment]
as expected. any way to disable the threaded builds on jenkins so the build logs are readable?

**Comment by MartijnKaijser** [comment]
Only with some tweaking. There might be other way but this should do for now.
Set to single threaded and only kept rtmp addon for binary to reduce log spam
http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1431/

edit:
should take a long time to build now :)

**Comment by notspiff** [comment]
Sniff. Smells like fart in here. mpd != rtmp.

**Comment by MartijnKaijser** [comment]
ffs :(
fixed http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1432/

**Comment by MartijnKaijser** [comment]
Builds are done. Hope it's useful

**Comment by MartijnKaijser** [comment]
@notspiff kicked a new build cause logs were gone
http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/lastSuccessfulBuild/
osx/linux build fine
android/ios/rpi failed

**Comment by notspiff** [comment]
thanks. can we retain them somehow? i wont be able to look at it before
monday earliest, festival this weekend and stuff..

**Comment by MartijnKaijser** [comment]
Hehe have fun. Doesn't seem so but building will be quiet with merge window closed so they will probably still be there

**Comment by akva2** [comment]
rerun please

**Comment by MartijnKaijser** [comment]
Just started 
http://jenkins.kodi.tv/job/BuildMulti-All/1457/

**Comment by MartijnKaijser** [comment]
@notspiff i've kicked a new build should have time

Edit:
kicked new build
http://jenkins.kodi.tv/job/BuildMulti-All/1498/

**Pull request merged**
