### PR TITLE
HDHomeRun PVR Addon

### PR DESCRIPTION
**Pull request by zcsizmadia**
I've started a native HDHomeRun PVR addon. It is automatically using the channel and guide data provided by the tuners. It is using the camek architecture and builds for Isengard and Jarvis as well.

Jarvis:
https://github.com/zcsizmadia/pvr.hdhomerun

Isengard:
https://github.com/zcsizmadia/pvr.hdhomerun/tree/Isengard

### CODE REVIEW

**Comment by hudokkow** [comment]
Thank you for submitting your addon.
There's already one addon with that name. Or similar. Please have a look at http://kodi.wiki/view/Add-on:HDHomeRun_Live_TV
I'm assuming it's not the same addon and that you verified they don't conflict with each other? Also, what's the difference between them?

Apart from that, 2 notes:
No need for 3 commits to add the addon to our repo. Please squash into one commit.

We like to keep binary addons under our control. Reason is it's easier for us if we have full write access. Makes bumping APIs, last minute fixes, etc. a lot less stressful. :wink: 

After the review process, assuming everything is OK and we won't have two addons going ninja on each other,  I'll push the addon to our account, create a team just for your addon and send you an invite. After all is setup, you'll have push rights for your addon and the future location <code>\- github.com/kodi-pvr/pvr.hdhomerun -</code> should be treated as upstream.

That is, if you're OK with this.

Anyway, before any of that, I need clarification about the 2 addons situation. Do they clash? What are the differences? Does your addon provide more functionality?

**Comment by zcsizmadia** [comment]
Thanks for your reply.
The Hdhomerun VIEW addon is a python video add-on Implementing its own guide like gui and browsing channels. One major disadvantahe of the VIEW addon is that you must exit the addon to be able to go back to the main menu.

My pvr.hdhomerun is native PVR addon, having the same interface as any other PVR addon, grid like guide etc. 

In my setup I have both installed and no clash at all. I've compoled and runtime tested windows, linux x86, linux x64 environments. Unfortunately I have no other build environments.

What you prposed above is fine with me.

Best regards,
Zoltan

**Comment by hudokkow** [comment]
Ah! And me thinking all this time it was a true pvr addon... Silly me.

I'll start the process, build test the addon with jenkins and keep you posted. Please squash the commits and point the addon to <code>https://github.com/kodi-pvr/pvr.hdhomerun</code>

**Comment by zcsizmadia** [comment]
Thanks!

Added Isengard branch for 15.x. The master is 16.x (Jarvis).

**Comment by hudokkow** [comment]
Some binary addons failed to build on jenkins (http://jenkins.kodi.tv/view/Addons/job/BINARY-ADDONS/298/)

Apparently everything is OK with pvr.hdhomerun but I'm going to double check.

**Comment by hudokkow** [comment]
All green across the board.
http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1073/

Correct the repo URL, squash the commits and we're good to go.
It's already very AM here so that's work for tomorrow.

**Comment by Jalle19** [comment]
We should get the addon transferred to kodi-pvr before we merge this IMO.

**Comment by hudokkow** [comment]
Addon already is under our account -> https://github.com/kodi-pvr/pvr.hdhomerun

@zcsizmadia, reason I only pushed master branch to our account is because Isengard cycle is closed. Therefore it's too late to add the addon to it.

**Comment by Jalle19** [comment]
Cool, thanks.

**Comment by hudokkow** [comment]
This can be closed. See https://github.com/xbmc/repo-binary-addons/pull/18

**Comment by zcsizmadia** [comment]
Cristiano,

Do you mind if I leave the Isengard branch there, or should I remove it?

Zoltan

**Comment by hudokkow** [comment]
Leave it. Bytes are cheap. :smile:

**Pull request closed without merging**
