### PR TITLE
[adsp] Enable more platforms

### PR DESCRIPTION
**Pull request by AchimTuran**
Still missing is Android for adsp.biquad.filters.

Furthermore I will create new branches or tags if they get stable enough.

Afterwards we can merge this PR.

Edit:
~~The WIP label is missing here and I'm not able to create it. That's the reason why I added it to the header of this PR.~~
From my side this commit is ready to merge.

### CODE REVIEW

**Comment by AchimTuran** [comment]
@MartijnKaijser 
If you want you can merge this commit to enable the build of the adsp on more platforms. adsp.biquad.filters is still missing because of some compiler flags, which is the reason why it is disabled on Android. If I fixed the issue I will create a new commit.

Here is the latest [Jenkins Log](http://jenkins.kodi.tv/job/BINARY-ADDONS/324/).

**Comment by MartijnKaijser** [comment]
adsp.biquad.filters fails to build on multiple platforms. Please fix or revert building on more platforms

**Comment by AchimTuran** [comment]
@MartijnKaijser
Do you have a build log for me?

**Comment by MartijnKaijser** [comment]
http://jenkins.kodi.tv/job/IOS/6769/
http://jenkins.kodi.tv/job/OSX-64/7569/

**Pull request merged**
