### PR TITLE
add pvr.zattoo

### PR DESCRIPTION
**Pull request by trummerjo**
This adds a Zattoo PVR Plugin.
zattoo is a german (and swiss) TV streaming provider.

### CODE REVIEW

**Comment by ksooo** [comment]
Please  tag the version you want to add. Example: https://github.com/xbmc/repo-binary-addons/blob/master/pvr.octonet/pvr.octonet.txt

**Comment by ksooo** [comment]
What is your relation to @rbuehlma which I know as the author of pvr.zattoo?

**Comment by trummerjo** [comment]
I'm the 'original' author of the zattoo plugin

**Comment by rbuehlma** [comment]
Sorry for the confusion. Yes, trummerjo is the author of the addon. I just adapted it to the new API and added some feature.

**Comment by ksooo** [comment]
> Sorry for the confusion. Yes, trummerjo is the author of the addon. 

 Okay, thanks for clarifying.

> Please tag the version you want to add. Example: https://github.com/xbmc/repo-binary-addons/blob/master/pvr.octonet/pvr.octonet.txt

 Replacing 'master' by '0.1.23' in pvr.zattoo.txt is okay, but not enough. ;-) You need to tag the code so that <code>git checkout 0.1.23</code> will work.

**Comment by trummerjo** [comment]
> You need to tag the code so that git checkout 0.1.23 will work.

makes sense ;) 
Tagged it

**Comment by ksooo** [comment]
your addon.xml.in feels a little bit 'underweight'. important stuff, like implemented pvr addon api version is missing. refer to https://github.com/kodi-pvr/pvr.hts/blob/master/pvr.hts/addon.xml.in#L9 to get a feeling what i mean

**Comment by ksooo** [comment]
your settings.xml contains hard coded German strings. this is a nogo. kodi default language is en_gb Please switch to translatable resources and commit only en_gb strings.po. The other translations (including German!) must be done using Transifex.

**Comment by ksooo** [comment]
do you have the copy rights for channel logos you have in your github repo? I doubt this.

**Comment by ksooo** [comment]
at least some of the source file license statements look wrong. example: https://github.com/trummerjo/pvr.zattoo/blob/master/src/client.h#L7

**Comment by ksooo** [comment]
... i fear there is some work to be done before we are ready to include your addon in the official kodi installation sets.

**Comment by rbuehlma** [comment]
About the channel logos: I received the prepared ones from a kodinerds.net user. So the right for these specific versions should not be a problem. But I'm not sure if channel logos can be included at all or if the permissions of each channel is required. In case of the later, we would need to remove them.

**Comment by trummerjo** [comment]
I was aware of that there is not everything fine yet to merge it.
But I needed the feedback to know what things i should fix and I'll do that.

**Comment by ksooo** [comment]
> I was aware of that there is not everything fine yet to merge it.

 Then it would have been nice to state that beforehand.

**Comment by ksooo** [comment]
i suggest to ask for this feedback in the pvr developer section of the official kodi forum. this is not a support channel.

**Comment by ksooo** [comment]
> About the channel logos: I received the prepared ones from a kodinerds.net user. So the right for these specific versions should not be a problem. But I'm not sure if channel logos can be included at all or if the permissions of each channel is required.

 i'm not a lawer, but in case of doubt i would not include those.

**Review by ksooo — CHANGES_REQUESTED** [review]
although this change is okay, the addon is definitely not yet ready for inclusion. See my other comments for details.

**Comment by rbuehlma** [comment]
I've added translations and missing meta data (PR is pending)
https://github.com/trummerjo/pvr.zattoo/pull/12

Also I created a thread about the inclusion of the logos:
http://forum.kodi.tv/showthread.php?tid=299281

**Comment by rbuehlma** [comment]
@ksooo 
There came up a questions if the licenses from the files can be removed if the license.txt is added (all of them are under GPLv2.

What is your opinion on this?
-> https://github.com/trummerjo/pvr.zattoo/pull/12#issuecomment-265705161

**Comment by MartijnKaijser** [comment]
Any update?

**Comment by rbuehlma** [comment]
Would my PR resolve all the open issues?

https://github.com/trummerjo/pvr.zattoo/pull/12

**Pull request closed without merging**
