### PR TITLE
[viz] - fix supported platforms for osx and ios

### PR DESCRIPTION
**Pull request by Memphiz**
I am a bit unsure about goom tbh - but i guess darwin was osx before ...

this is against master (don't know how those branches are handled)

### CODE REVIEW

**Comment by Montellese** [comment]
IIRC `darwin` should be `osx` as `ios` has already been `ios` before. But I'm sure you know best which addons should build on which platforms.

**Comment by Memphiz** [comment]
Then this PR should be fine (waveform was always available on ios - no clue why it had only "darwin" in the platforms.txt then).

**Comment by Memphiz** [comment]
We have no chance yet to compile test those PRs right?

**Comment by Montellese** [comment]
Only on win32 with my jenkins test job.

**Pull request merged**
