### PR TITLE
Add X-Arcade Tankstick driver

### PR DESCRIPTION
**Pull request by garbear**
This adds a driver for the X-Arcade Tankstick: https://github.com/kodi-game/peripheral.xarcade

xarcade

Driver is disabled by default. Someday I hope to have auto detection that can enable drivers when their device is connected.

Thanks to X-Arcade for donating a Tankstick.

Tested on Linux x64. Add-on has been included in LE for a while now and should soon be not broken.

TODO:
- [x] Wiki entry on installing `80-xarcade.rules`

### CODE REVIEW

**Comment by Rechi** [comment]
add travis ci and debian packaging files to the repo before merging this PR

edit: version in peripheral.xarcade/addon.xml.in also was never bumped during various big updates

**Comment by garbear** [comment]
@Rechi can you check https://github.com/kodi-game/peripheral.xarcade/pull/4?

**Comment by garbear** [comment]
What do you mean about bumping the version?

**Comment by Rechi** [comment]
bump https://github.com/kodi-game/peripheral.xarcade/blob/edda1d4/peripheral.xarcade/addon.xml.in#L4. 
Version was never increased since the addon was initial written for the Krypton API and then updated multiple times for Leia changes. That isn't how versioning works. You have to at least bump it when implementing a new API.

**Comment by garbear** [comment]
I consider this the 1.0 release, but I can update to 1.1 for the API changes

**Comment by garbear** [comment]
Brief wiki article is up: https://kodi.wiki/view/HOW-TO:X-Arcade_Tankstick

**Review by Rechi — APPROVED** [review]

**Pull request merged**
