### PR TITLE
Add pvr.plutotv

### PR DESCRIPTION
**Pull request by flubshi**
This PR adds new PVR addon **pvr.plutotv**.

[Pluto.tv](http://pluto.tv/) is a free (_paid_ by ads) streaming provider that is available in some countries. In germany, it provides 75 TV channels. In some countries user accounts are available for this service. Since it is not available here, I cannot test and implement user authentication. But channels are available without authentication.

## Current state
The plugin implements some basic features, but some are not implement yet because they are not available everywhere / here.

**What works is:**
- List TV channels
- EPG (start, end, title, description, images, genre)
- Play TV streams

## Note
~~This addon is implemented for the upcoming C++ addon interface. Therefore, please **do not merge before** https://github.com/xbmc/xbmc/pull/16485 is merged.~~

~~I already created this PR now, to get some feedback about required changes and to give you more time to review.~~

@ksooo I would like to invite you to pvr.plutotv repository, if you agree.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Can you test your pvr.plutotv with now merged Kodi changes and also to look then about the Jenkins way (the Jenkinsfile on addon).

Ping @lrusak

**Comment by lrusak** [comment]
pvr.plutotv has been added to jenkins

**Comment by flubshi** [comment]
Thanks for adding to jenkins!

I tested it with todays Kodi master (0bb0b9f) - seems to work as expected. :)

**Comment by Lunatixz** [comment]
@flubshi very nice... Thanks for the PVR! If you need help with Pluto.TV's API feel free to contact me.

**Comment by flubshi** [comment]
> @flubshi very nice... Thanks for the PVR! If you need help with Pluto.TV's API feel free to contact me.

Thanks @Lunatixz for this offer. I borrowed the most requests from the existing video addon for pluto.tv. In addition, I captured the API requests from the Android App. As mentioned above, the login mechanism is not yet implemented. At the moment, it would help to find some more users testing the pvr addon and maybe in future testing the authentication. 

Another question is, if the addon gets accepted as official kodi pvr addon. If not, I am not interested in continuing the development.

**Comment by flubshi** [comment]
Are there any plans to merge this for matrix?

**Comment by flubshi** [comment]
It looks like nobody of team kodi in interested in merging this. Due to lack of time at the moment, I close this Pull Request.

If someone else is interested in continuing development of pvr.plutotv: feel free, it's GPL :)

**Comment by ksooo** [comment]
Oh, I guess it just got overlooked. Sorry. 

If you are still willing to maintain that add-on please reopen this PR and I will be happy to merge.

**Comment by ksooo** [comment]
Hmm, looking at the latest commit on Matrix branch being from May 28, I guess that you need to adapt to latest Matrix API changes before we can merge this, @flubshi

**Comment by ksooo** [comment]
> If you are still willing to maintain that add-on please reopen this PR and I will be happy to merge.

@flubshi would you be willing to start working on this add-on again? I would be happy to assist to get it ready for Matrix and Nexus ff.

**Comment by flubshi** [comment]
> > If you are still willing to maintain that add-on please reopen this PR and I will be happy to merge.
> 
> @flubshi would you be willing to start working on this add-on again? I would be happy to assist to get it ready for Matrix and Nexus ff.

Unfortunately, my job consumes to much time to work on open source projects atm. If there will be some time in neat future, I would like to focus on pvr.waipu. So no plans to work on pvr.plutotv next months :(

**Comment by ksooo** [comment]
@flubshi mind if I take over, fork your repo and finally move to kodi-pvr?

**Comment by flubshi** [comment]
sure, feel free to fork/move to kodi-pvr :)

**Comment by ksooo** [comment]
Cool, will give it a go.

**Comment by ksooo** [comment]
Done. pvr.plutotv is now part of kodi-pvr.

**Pull request closed without merging**
