### PR TITLE
[screensaver.pingpong] v1.0.0

### PR DESCRIPTION
**Pull request by notspiff**
Only linux and windows has been tested.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
nice :)
atm Kodi master uses master branch of this repo so "Jarvis" isn't yet used as it seems. Looks like master/jarvis are still copies of each other. You could also set git SHA to master so it will always fetch new fixes you might include and at actual branch time for release we switch to specified versions.

Maybe disable osx till some osx dev could take it for a testdrive? 
@Montellese ping as you know how this "new" system works.

**Comment by notspiff** [comment]
it should (tm) just build on osx. you need a trigger for this shit ;)

**Comment by Montellese** [comment]
Right now we still use the `master` branch because we don't have any repositories where we can upload binary addons built through jenkins. Once we have that we absolutely must use the `jarvis` branch where every binary addon is defined by a specific git SHA. We can still use the `master` branch in Kodi's `master` branch for developer convenience but we cannot upload those builds to a repository.

I can check if this builds fine on win32.

**Comment by Montellese** [comment]
Works fine on win32.

**Comment by MartijnKaijser** [comment]
let's ask @Memphiz nicely for an osx check :)

**Comment by Memphiz** [comment]
i have no clue what i need to do to compile this with my checked out mainline kodi tree - i can inject it into project/cmake/addons and manually build it if this is enough ...

**Comment by Montellese** [comment]
@Memphiz: I injected the two `.txt` files into `project/cmake/addons/addon` (the directory might not exist), built the addon, started kodi, selected the Ping Pong screensaver and used the preview functionality to check it.

**Comment by Memphiz** [comment]
works on osx once this pr is merged:

https://github.com/notspiff/screensaver.pingpong/pull/2

**Comment by MartijnKaijser** [comment]
@notspiff could you this one to master branch? Once we'll branch we can also put it in Jarvis branch

**Pull request closed without merging**
